try {
    throw new Error("Deu um problema no c√≥digo");
} catch (error) {
    console.log(error.name + ": " + error.message);
}